### PR TITLE
Add detekt

### PR DESCRIPTION
**Pull request by youngman3009**
Added Detekt as a dependency
Added Detekt to CI analyse stage

### CODE REVIEW

**Comment by Chesire** [comment]
I pulled down your branch and tried running Detekt, but I don't think it worked? I added a few problems to a Fragment and it didn't detekt them.
I think it needs to be setup similar to https://github.com/detekt/detekt#with-gradle in the projects `build.gradle`, as a plugin, with the config section

**Review by ChrisJanusiewicz — APPROVED** [review]

**Comment by youngman3009** [comment]
@Chesire would you be able to offer any help please? Its failing because of the inner class not having documentation, but I don't think that that is wrong as its not public. I've set max issues to 0 so that any issues cause it to fail, but is there a way of making it slightly less fussy, or is this right?!

**Comment by Chesire** [comment]
I think the inner class could be made `private` to avoid this, failing that `internal` would also suffice I think. It shouldn't really be used out of that file.

**Comment by youngman3009** [comment]
It can't be made private due to it needing to be public for `override fun onBindViewHolder(holder: ViewHolder, position: Int)` so I have just added some basic kdoc. I believe after this, this PR should be ready!

**Review by Chesire — APPROVED** [review]

**Pull request merged**
